// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    aws_project_region: 'ap-southeast-1',
    aws_cognito_identity_pool_id: 'ap-southeast-1:66d80926-60db-4e73-9c90-42c793eeba35',
    aws_cognito_region: 'ap-southeast-1',
    aws_user_pools_id: 'ap-southeast-1_vOWnMIATs',
    aws_user_pools_web_client_id: '1kh3d0dfgq3p9ngkpsd2rbmjsu',
    oauth: {
        domain: 'smartchat-staging.auth.ap-southeast-1.amazoncognito.com',
        scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'https://smartchat.job4u.vn/,https://smartchat.job4u.io/',
        redirectSignOut: 'https://smartchat.job4u.vn/,https://smartchat.job4u.io/',
        responseType: 'code',
    },
    federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
    aws_appsync_graphqlEndpoint: 'https://au4pgu2eurgthexxlk57ybobk4.appsync-api.ap-southeast-1.amazonaws.com/graphql',
    aws_appsync_region: 'ap-southeast-1',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
    aws_appsync_apiKey: 'da2-jj4thm6bmngpthhobq7vzzekj4',
    aws_user_files_s3_bucket: 'smartchat-staging',
    aws_user_files_s3_bucket_region: 'ap-southeast-1',
};

export default awsconfig;
